# This is a basic workflow to help you get started with Actions

name: CI
on: 
  push:
    branches: [ master ]  
    
  workflow_dispatch:

jobs:

  update-build:    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2    
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
          
    - name: Check for updated dependencies      
      run: yarn
        
    - name: Build typescript package
      run: yarn build

    - name: Push build to build branch
      uses: EndBug/add-and-commit@v7.2.0
      with:                          
        message: "Updates package typescript build"                             
